FROM nginx:1.19.10 as base

LABEL org.opencontainers.image.authors=devops@switch.com.uy
LABEL org.opencontainers.image.licenses=MIT

WORKDIR /usr/share/nginx/html

COPY ./security-headers.conf /etc/nginx/security-headers.conf

COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

##############################################

FROM node:16.5.0 as build-base

WORKDIR /app

COPY . .

ENV PATH /app/node_modules/.bin:$PATH

RUN yarn install --frozen-lockfile \
    && yarn cache clean --force

################################################

FROM node:16.5.0 as dev

ENV NODE_ENV=development

EXPOSE 4200
ENV PORT 4200

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn config list
RUN yarn install \
    && yarn cache clean --force

ENV PATH /app/node_modules/.bin:$PATH

CMD [ "yarn", "start" ]

###################################

FROM build-base as build

RUN [ "ng", "build", "backoffice", "--configuration", "production" ]

##########################################################

FROM base as prod

LABEL org.opencontainers.image.title="tsp backoffice dockerfile"
LABEL us.cadynce.web.nodeversion=$NODE_VERSION

COPY --from=build ./app/dist/backoffice .
