version: "3.7"

services:
  server-db-data:
#if (EnableMysqlSupport)
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_DATA}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER_DATA}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_DATA}
      - TZ=America/Montevideo
    healthcheck:
      test: /usr/bin/mysql --user=${MYSQL_USER_DATA} --password=${MYSQL_PASSWORD_DATA} --execute "SHOW DATABASES;"
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 10s
#endif
#if (!EnableMysqlSupport)
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      - TZ=America/Montevideo
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SA_PASSWORD}
      - MSSQL_PID=Express
#endif
    networks:
      - backend
      
@*#if (EnableRedisSupport)
  Clean.Architecture-redis:
    image: redis:6.2.6-alpine
    healthcheck:
      test: redis-cli -h 127.0.0.1
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend
#endif*@

@*#if (EnableKibanaSupport)
  Clean.Architecture-elasticsearch:
    container_name: Clean.Architecture-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend
      
  Clean.Architecture-kibana:
    container_name: Clean.Architecture-kibana
    image: docker.elastic.co/kibana/kibana:7.14.1
    environment:
      - ELASTICSEARCH_URL=http://Clean.Architecture-elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://Clean.Architecture-elasticsearch:9200
    networks:
      - backend
    depends_on:
      - Clean.Architecture-elasticsearch
    ports:
      - 5601:5601
#endif*@

volumes:
  databases:

networks:
  backend: {}