version: "3.7"

services:
  server-db-data:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_DATA}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER_DATA}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_DATA}
      - TZ=America/Montevideo
    healthcheck:
      test: /usr/bin/mysql --user=${MYSQL_USER_DATA} --password=${MYSQL_PASSWORD_DATA} --execute "SHOW DATABASES;"
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 10s
    networks:
      - backend
      
  tsp-redis:
    image: redis:6.2.6-alpine
    healthcheck:
      test: redis-cli -h 127.0.0.1
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend

  tsp-elasticsearch:
    container_name: tsp-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend
      
  tsp-kibana:
    container_name: tsp-kibana
    image: docker.elastic.co/kibana/kibana:7.14.1
    environment:
      - ELASTICSEARCH_URL=http://tsp-elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://tsp-elasticsearch:9200
    networks:
      - backend
    depends_on:
      - tsp-elasticsearch
    ports:
      - 5601:5601
      

volumes:
  databases:

networks:
  backend: {}